title: Agniva Chakraborty
logo: /assets/img/Profile Pic.jpg
#description: Minimal is a theme for GitHub Pages.
[View LinkedIn Profile](https://www.linkedin.com/in/agnivachakraborty/)
show_downloads: true
theme: jekyll-theme-minimal
